service: baap-academic-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'prod'}
  region: ap-south-1
  memorySize: 256


functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'
